spring:
  config:
    activate:
      on-profile: "dev"
  servlet:
    multipart:
      max-file-size: 1024MB    # 最大文件大小1GB
      max-request-size: 1024MB # 最大请求大小1GB
      enabled: true

server:
  port: 8081

logging:
  level:
    com.example.demo: DEBUG
    org.springframework.web: DEBUG

app:
  environment: "development"
  debug: true
  file:
    uploadDir: "${UPLOAD_DIR:E:/docker/app/file}"
    token-secret: fk521314